hyperparameter-distributions:
  # Optim args
  lr: [1e-4, 5e-5]
  optim_beta2: [.95, .98, .99, .999]
  optim_beta1: [.9, .95, .99] #.8
  gclip: [.5, 1, 5, 10]
  wd: [1e-1, 1e-2, 1e-3, 1e-4]

  # Train args
  batch_size: [32, 64] #128

  # Model args
  transformer_nheads: [8, 16] #4
  router_dropout: [.1, .2] #.5
  random_positional_max_len: [12, 16, 20] #32