hyperparameter-distributions:
  tied_io_languages: [1]
  add_eob_to_memory: [1]
  cons_only: [1]
  early_stop_epochs: [1000]
  filler_noise_location: ['input']
  filler_noise_std: 1
  positional_embedding_type: ['sinusoidal']
  d_filler: 64


  ctrl_hidden_dim: 64

  # Optim args
  lr: [1e-4]
  optim_beta2: [.95]
  optim_beta1: [.9]

  gclip: [1]
  wd: [1e-1]

  # Train args
  batch_size: [64]

  # Model args
  transformer_nheads: [4]
  router_dropout: [.1]

  num_warmup_steps: [10000]
  scheduler: [cosine]
  steps: [60000]

  train_log_freq: 20

