#xt run --max-node-duration=12h --target=sing-h100 --request=1 --description="trial run for final geoquery"
#  --runs=4 --nodes=4 --hp-config=hyperparameter_search/shaw_geo_hparams.yaml main.py --wandb_name=neurips_geo_final
#--wandb_group=neurips --use_wandb
hyperparameter-distributions:
  task_path: [
    'shaw_geo/v1/length',
    'shaw_geo/v1/standard',
    'shaw_geo/v1/template',
    'shaw_geo/v1/tmcd',
  ]

  test_most_recent_checkpoint: 1
  max_tree_depth: 11
  max_filled_roles: 2048
  dtm_layers: 22
  validate_every_num_epochs: 10
  use_vocab_info: 0
  random_positional_max_len: 44 # Used to be 33 for earlier trial runs, make sure 44 works

  tied_io_languages: [1]
  add_eob_to_memory: [1]
  cons_only: [1]
  early_stop_epochs: [1000]
  filler_noise_location: ['input']
  filler_noise_std: 1
  positional_embedding_type: ['sinusoidal']
  d_filler: 128

  ctrl_hidden_dim: 256
  transformer_nheads: [8]

  # Optim args
  lr: [1e-4]
  optim_beta2: [.95]
  optim_beta1: [.9]

  gclip: [1]
  wd: [1e-1]

  # Train args
  batch_size: [32]

  # Model args
  router_dropout: [.1]

  num_warmup_steps: [10000]
  scheduler: [cosine]
  steps: [50000]

  train_log_freq: 20

